// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"code-practice/go/clean-architecture/repository-interface/4-di-wire/application"
	"code-practice/go/clean-architecture/repository-interface/4-di-wire/domain"
	"code-practice/go/clean-architecture/repository-interface/4-di-wire/persistence"
	"database/sql"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeBoxUseCase は「BoxUseCaseが欲しい。材料はこれ」と宣言するだけのinjector。
// 中身の組み立ては `wire` コマンドが wire_gen.go に生成する
func InitializeBoxUseCase(db *sql.DB) *application.BoxUseCase {
	boxRepository := persistence.NewBoxRepository(db)
	domainBoxRepository := newCachedRepository(boxRepository)
	boxUseCase := application.NewBoxUseCase(domainBoxRepository)
	return boxUseCase
}

// wire.go:

// newCachedRepository は素のBoxRepositoryをキャッシュで包み、domain.BoxRepositoryとして返す
func newCachedRepository(inner *persistence.BoxRepository) domain.BoxRepository {
	return persistence.NewCachedBoxRepository(inner)
}
